--- 
extends: existence
message: "Avoid generic link text like '%s'. Use descriptive link text instead."
description: >
  Descriptive link text improves accessibility and SEO.
level: warning
ignorecase: true
scope: text
tokens:
  - 'click here'
  - 'read more'
  - 'more info'
  - 'here'

