---
extends: substitution
message: "Use %s instead of '%s' for consistency."
description: >
  Replaces outdated, unclear, or informal terms with more inclusive or formal alternatives
  for clarity, accessibility, and consistency across Umbraco documentation.
link: https://docs.umbraco.com/contributing/documentation/style-guide#terms-general
level: warning
ignorecase: true
swap:
  '(?<!\b(?:branch|template)\s)master(?!\s(?:branch|template))': "'primary'"  # Avoid false positives in valid Git and template contexts
  'slave': "'secondary'"
  'blacklist': "'deny list'"
  'whitelist': "'allow list'"
  'etc\.': "'and so on'"
  '\b(e\.g\.|eg)\b': "'for example'"
  '\b(i\.e\.|ie)\b': "'that is'"
  'aka': "'also known as'"
  'docs': "'documentation'"
