---
extends: substitution
message: "Use %s instead of '%s.' for consistency."
description: >
  Ensures consistent naming and capitalization for Umbraco-specific terms
link: https://docs.umbraco.com/contributing/documentation/style-guide#umbraco-terms
level: warning
scope: text
swap:
  'back office': "'backoffice'"               
  'back-office': "'backoffice'"
  '(?<![\.\/@])umbraco': "'Umbraco'"           #Avoids false positives like URLs or emails
  'document type': "'Document Type'"
  'document-type': "'Document Type'"
  'doc type': "'Document Type'"
  'doc-type': "'Document Type'"
  'data-type': "'Data Type'"
  'data type': "'Data Type'"
  'heartcore': "'Heartcore'"
  'umbraco cloud': "'Umbraco Cloud'"
  'umbraco deploy': "'Umbraco Deploy'"
  'umbraco forms': "'Umbraco Forms'"
  'umbraco heartcore': "'Umbraco Heartcore'"