name: Check Links in Pull Requests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Markdown files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.md$' || true)
          CHANGED_FILES="${CHANGED_FILES//$'\n'/ }"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Changed Markdown files: $CHANGED_FILES"

      - name: Skip if no Markdown files changed
        if: env.CHANGED_FILES == ''
        run: |
          echo "No Markdown files changed. Skipping link check."
          exit 0

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run Lychee and format output
        run: |
          mkdir -p lychee
          lychee ${{ env.CHANGED_FILES }} \
            --include-fragments \
            --no-progress \
            --format checkstyle \
            > lychee/checkstyle.xml
          cat lychee/checkstyle.xml

      - name: Annotate broken links inline
        uses: reviewdog/action-pr-review@v1
        with:
          name: lychee
          reporter: github-pr-review
          level: error
          input: lychee/checkstyle.xml
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
