name: 'Check Markdown Links'

on: [pull_request]

jobs:
  check-markdown-links:
    name: Check links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check markdown links
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true