name: Check Links in Pull Requests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Markdown files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.md$' || true)
          CHANGED_FILES="${CHANGED_FILES//$'\n'/ }"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Changed Markdown files: $CHANGED_FILES"

      - name: Skip if no Markdown files changed
        if: env.CHANGED_FILES == ''
        run: |
          echo "No Markdown files changed. Skipping link check."
          exit 0

      - name: Run Lychee
        id: run-lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: |
            --no-progress
            --include-fragments
            --format detailed
            ${{ env.CHANGED_FILES }}
          output: lychee/out_raw.md
          fail: false

      - name: Format Lychee report (user-friendly)
        id: format-report
        if: always()
        run: |
          mkdir -p lychee
          echo "🚨 **Link Checker found issues in this PR**" > lychee/comment.md
          echo "" >> lychee/comment.md

          awk '
            /^Errors in / {
              file=$3
              gsub("^/home/runner/work/UmbracoDocs/UmbracoDocs/", "", file)
              print "\n**File:** " file >> "lychee/comment.md"
              next
            }
          
            /\[ERROR\]/ {
              msg = $0
              sub(/^- \[ \] /, "", msg)                # remove leading task list
              sub(/^\[ERROR\] /, "", msg)             # remove [ERROR]
              gsub("^file:///home/runner/work/UmbracoDocs/UmbracoDocs/", "", msg)
              print "⚓ Anchor not found → " msg >> "lychee/comment.md"
              next
            }
          
            /\[404\]/ {
              msg = $0
              sub(/^- \[ \] /, "", msg)
              sub(/^\[404\] /, "", msg)
              print "❌ 404 Not Found → " msg >> "lychee/comment.md"
              next
            }
          
            /\[301\]|\[302\]/ {
              msg = $0
              sub(/^- \[ \] /, "", msg)
              sub(/^\[(301|302)\] /, "", msg)
              print "🔀 Redirect → " msg >> "lychee/comment.md"
              next
            }
          
            /Timeout/ {
              msg = $0
              print "⏳ Timeout → " msg >> "lychee/comment.md"
              next
            }
          ' lychee/out_raw.md


          if [ -s lychee/comment.md ]; then
            echo "has_content=true" >> $GITHUB_OUTPUT
          else
            echo "has_content=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment broken links
        if: always() && (env.CHANGED_FILES != '') && (steps.format-report.outputs.has_content == 'true')
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: lychee/comment.md
          recreate: true

      - name: Fail workflow if broken links
        if: steps.format-report.outputs.has_content == 'true'
        run: |
          echo "❌ Broken links detected. Please review the PR comment for details."
          exit 1
