name: 'Check Markdown Links'

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  check-markdown-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest

    steps:
     # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
        
     # Step 2: Run Linkspector with reviewdog
      - name: Run Linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          config_file: .linkspector.yml   # ✅ point to your config
          fail_on_error: true
          
