name: Check Links in Pull Requests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Get changed Markdown files
      - name: Get changed Markdown files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.md$' || true)
          CHANGED_FILES="${CHANGED_FILES//$'\n'/ }"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Changed Markdown files: $CHANGED_FILES"

      # 3️⃣ Skip if no Markdown files changed
      - name: Skip if no changed Markdown files
        if: env.CHANGED_FILES == ''
        run: |
          echo "No Markdown files changed. Skipping link check."
          exit 0

      # 4️⃣ Install Lychee
      - name: Install Lychee
        run: |
          curl -sL https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv lychee /usr/local/bin/

      # 5️⃣ Run Lychee with Checkstyle output including line numbers
      - name: Run Lychee
        run: |
          mkdir -p lychee
          # Use --line to include line numbers, --format checkstyle for Reviewdog
          lychee ${{ env.CHANGED_FILES }} \
            --include-fragments \
            --no-progress \
            --format checkstyle \
            --line \
            > lychee/checkstyle.xml
          cat lychee/checkstyle.xml

      # 6️⃣ Annotate broken links inline using Reviewdog
      - name: Annotate broken links in PR
        uses: reviewdog/action-reviewdog@v0.12.1
        with:
          name: lychee
          reporter: github-pr-review
          level: error
          input: lychee/checkstyle.xml
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
